version: '3'

services:
  primary-postgres:
    image: postgres:9.6
    env_file:
      - primary-postgres.env
    ports:
      - "5432:5432"
    volumes:
      - primary-data:/var/lib/postgresql/data
    command: postgres -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10

volumes:
  primary-data: